defaultIndent: "  "

modifyLineBreaks:
  textWrapOptions:
    columns: 100
    removeBlockLineBreaks: 1
    when: after
    blocksFollow:
      other: \\\]|\\item(?:\h|\[)
    blocksBeginWith:
      A-Z: 1
      a-z: 1
    huge: overflow
